export const PAYMENT_ERROR_STATUS = {
  INVALID_ORDER_ID: 400,
  ORDER_NOT_FOUND: 404,
  Forbidden: 403,
  INVALID_AMOUNT: 400,
  AMOUNT_MISMATCH_WITH_INTENT: 409,
  PAYMENT_SERVICE_UNAVAILABLE: 502,
  PAYMENT_INTENT_FAILURE: 400,
  PAYMENT_NOT_FOUND: 404,
  PAYMENT_INTENT_CANCELLATION_FAILURE: 500,
};
