export const ADDRESS_ERROR = {
  ADDRESS_CREATE_FAILED: "ADDRESS_CREATE_FAILED",
  ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",
  ADDRESS_SAVE_FAILED: "ADDRESS_SAVE_FAILED",
};

export const ADDRESS_ERROR_STATUS = {
  ADDRESS_CREATE_FAILED: 500,
  ADDRESS_NOT_FOUND: 404,
  ADDRESS_SAVE_FAILED: 500,
};

export const AUTH_ERROR = {
  ACCOUNT_CREATION_FAILED: "ACCOUNT_CREATION_FAILED",
  ACCOUNT_CREATED_SESSION_FAILED: "ACCOUNT_CREATED_SESSION_FAILED",
  EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE", // 회원가입
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS", // 로그인
  INVALID_INVITATION: "INVALID_INVITATION",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN", // 비밀번호 재설정
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN", // JWT 자체가 조작/malformed
  INVITATION_CREATE_FAILED: "INVITATION_CREATE_FAILED",
  INVITATION_INVALIDATE_FAILED: "INVITATION_INVALIDATE_FAILED",
  LAST_LOGIN_UPDATE_FAILED: "LAST_LOGIN_UPDATE_FAILED",
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  PASSWORD_UPDATE_FAILED: "PASSWORD_UPDATE_FAILED",
  REFRESH_TOKEN_UPDATE_FAILED: "REFRESH_TOKEN_UPDATE_FAILED",
  SAME_PASSWORD: "SAME_PASSWORD",
  SESSION_EXPIRED: "SESSION_EXPIRED", // JWT 자체가 유효하지 않거나 만료됨
  SESSION_REVOKED: "SESSION_REVOKED", // DB의 refreshToken과 불일치/삭제됨
  STRIPE_ID_UPDATE_FAILED: "STRIPE_ID_UPDATE_FAILED",
  USER_NAME_UPDATE_FAILED: "USER_NAME_UPDATE_FAILED",
  USER_NOT_FOUND: "USER_NOT_FOUND", // (인증은 됐지만 유저 레코드가 없음)
};

export const AUTH_ERROR_STATUS = {
  ACCOUNT_CREATED_SESSION_FAILED: 500,
  ACCOUNT_CREATION_FAILED: 500,
  EMAIL_ALREADY_IN_USE: 409,
  INCORRECT_PASSWORD: 401,
  INVALID_ACCESS_TOKEN: 401,
  INVALID_CREDENTIALS: 401,
  INVALID_INVITATION: 403,
  INVALID_REFRESH_TOKEN: 401,
  INVALID_RESET_TOKEN: 400,
  INVITATION_CREATE_FAILED: 500,
  INVITATION_INVALIDATE_FAILED: 500,
  LAST_LOGIN_UPDATE_FAILED: 500,
  MISSING_REFRESH_TOKEN: 400,
  PASSWORD_UPDATE_FAILED: 500,
  REFRESH_TOKEN_UPDATE_FAILED: 500,
  SAME_PASSWORD: 400,
  SESSION_EXPIRED: 401,
  SESSION_REVOKED: 403,
  STRIPE_ID_UPDATE_FAILED: 500,
  USER_NAME_UPDATE_FAILED: 500,
  USER_NOT_FOUND: 401,
};

export const CART_ERROR = {
  INVALID_CART_ITEM: "INVALID_CART_ITEM",
};

export const CART_ERROR_STATUS = {
  INVALID_CART_ITEM: 400,
};

export const MENU_ERROR = {
  INVALID_FIELD: "INVALID_FIELD",
  MENU_ALREADY_EXISTS: "MENU_ALREADY_EXISTS",
  MENU_NOT_FOUND: "MENU_NOT_FOUND",
};

export const MENU_ERROR_STATUS = {
  INVALID_FIELD: 400,
  MENU_NOT_FOUND: 404,
  MENU_ALREADY_EXISTS: 409,
};

export const ORDER_ERROR = {
  CHARGE_NOT_FOUND: "CHARGE_NOT_FOUND",
  EMPTY_ORDER_ITEMS: "EMPTY_ORDER_ITEMS",
  FORBIDDEN: "FORBIDDEN",
  INVALID_ORDER_ID: "INVALID_ORDER_ID",
  ITEMS_UNAVAILABLE: "ITEMS_UNAVAILABLE",
  ORDER_CREATE_FAILED: "ORDER_CREATE_FAILED",
  ORDER_NOT_CANCELLABLE: "ORDER_NOT_CANCELLABLE",
  ORDER_NOT_EXPIRABLE: "ORDER_NOT_EXPIRABLE",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_STATUS_CONFLICT: "ORDER_STATUS_CONFLICT",
  PAYMENT_INTENT_NOT_FOUND: "PAYMENT_INTENT_NOT_FOUND",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_NOT_REFUNDABLE: "PAYMENT_NOT_REFUNDABLE",
  PAYMENT_STATUS_CONFLICT: "PAYMENT_STATUS_CONFLICT",
  POST_DB_FAILURE: "POST_DB_FAILURE",
  POST_REFUND_DB_FAILURE: "POST_REFUND_DB_FAILURE",
  REFUND_FAILED: "REFUND_FAILED",
};

export const ORDER_ERROR_STATUS = {
  EMPTY_ORDER_ITEMS: 400,
  INVALID_ORDER_ID: 400,
  ITEMS_UNAVAILABLE: 400,
  FORBIDDEN: 403,
  CHARGE_NOT_FOUND: 404,
  ORDER_NOT_FOUND: 404,
  PAYMENT_INTENT_NOT_FOUND: 404,
  PAYMENT_NOT_FOUND: 404,
  ORDER_NOT_CANCELLABLE: 409,
  ORDER_NOT_EXPIRABLE: 409,
  ORDER_STATUS_CONFLICT: 409,
  PAYMENT_NOT_REFUNDABLE: 409,
  PAYMENT_STATUS_CONFLICT: 409,

  ORDER_CREATE_FAILED: 500,
  POST_DB_FAILURE: 500,
  POST_REFUND_DB_FAILURE: 500,
  REFUND_FAILED: 502,
};

export const PAYMENT_ERROR = {
  AMOUNT_MISMATCH_WITH_INTENT: "AMOUNT_MISMATCH_WITH_INTENT",
  CARD_NOT_FOUND: "CARD_NOT_FOUND",
  CHARGE_NOT_FOUND: "CHARGE_NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  INVALID_CARD_ID: "INVALID_CARD_ID",
  INVALID_ORDER_ID: "INVALID_ORDER_ID",
  INVALID_PAYMENT_INTENT: "INVALID_PAYMENT_INTENT",
  INVALID_PAYMENT_METHOD_ID: "INVALID_PAYMENT_METHOD_ID",
  INVALID_SAVE_CARD_FLAG: "INVALID_SAVE_CARD_FLAG",
  INVALID_SET_DEFAULT_FLAG: "INVALID_SET_DEFAULT_FLAG",
  ORDER_NOT_CANCELLABLE: "ORDER_NOT_CANCELLABLE",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_STATUS_CONFLICT: "ORDER_STATUS_CONFLICT",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_INTENT_CANCELLATION_FAILURE: "PAYMENT_INTENT_CANCELLATION_FAILURE",
  PAYMENT_INTENT_FAILURE: "PAYMENT_INTENT_FAILURE",
  PAYMENT_INTENT_IDEMPOTENCY_CONFLICT: "PAYMENT_INTENT_IDEMPOTENCY_CONFLICT",
  PAYMENT_INTENT_NOT_FOUND: "PAYMENT_INTENT_NOT_FOUND",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_NOT_REFUNDABLE: "PAYMENT_NOT_REFUNDABLE",
  PAYMENT_SERVICE_UNAVAILABLE: "PAYMENT_SERVICE_UNAVAILABLE",
  PAYMENT_STATUS_CONFLICT: "PAYMENT_STATUS_CONFLICT",
  POST_PAYMENT_INTENT_DB_FAILURE: "POST_PAYMENT_INTENT_DB_FAILURE",
  POST_REFUND_DB_FAILURE: "POST_REFUND_DB_FAILURE",
  REFUND_FAILED: "REFUND_FAILED",
};

export const PAYMENT_ERROR_STATUS = {
  PAYMENT_FAILED: 400,
  INVALID_AMOUNT: 400,
  INVALID_CARD_ID: 400,
  INVALID_ORDER_ID: 400,
  INVALID_PAYMENT_INTENT: 400,
  INVALID_PAYMENT_METHOD_ID: 400,
  INVALID_SAVE_CARD_FLAG: 400,
  INVALID_SET_DEFAULT_FLAG: 400,
  ITEMS_UNAVAILABLE: 400,
  PAYMENT_INTENT_FAILURE: 400,

  FORBIDDEN: 403,

  CARD_NOT_FOUND: 404,
  ORDER_NOT_FOUND: 404,
  PAYMENT_NOT_FOUND: 404,
  PAYMENT_INTENT_NOT_FOUND: 404,
  CHARGE_NOT_FOUND: 404,

  AMOUNT_MISMATCH_WITH_INTENT: 409,
  ORDER_NOT_CANCELLABLE: 409,
  ORDER_STATUS_CONFLICT: 409,
  PAYMENT_INTENT_IDEMPOTENCY_CONFLICT: 409,
  PAYMENT_NOT_REFUNDABLE: 409,
  PAYMENT_STATUS_CONFLICT: 409,

  PAYMENT_INTENT_CANCELLATION_FAILURE: 500,
  POST_PAYMENT_INTENT_DB_FAILURE: 500,
  POST_REFUND_DB_FAILURE: 500,
  POST_DB_FAILURE: 500,

  PAYMENT_SERVICE_UNAVAILABLE: 502,
  REFUND_FAILED: 502,
};

export const REFRESH_LOG_CONFIG = {
  [AUTH_ERROR.MISSING_REFRESH_TOKEN]: {
    level: "warn",
    message:
      "No refresh token present (normal for logged-out or first-time visitors)",
    clientMessage: "Please sign in again.",
  },
  [AUTH_ERROR.SESSION_EXPIRED]: {
    level: "warn",
    message: "Refresh token expired (normal)",
    clientMessage:
      "For your security, you've been logged out. Please sign in again.",
  },
  [AUTH_ERROR.INVALID_REFRESH_TOKEN]: {
    level: "warn",
    message: "Invalid/tampered refresh token",
    clientMessage:
      "For your security, you've been logged out. Please sign in again.",
  },
  [AUTH_ERROR.SESSION_REVOKED]: {
    level: "warn",
    message: "Invalid refresh token",
    clientMessage:
      "For your security, you've been logged out. Please sign in again.",
  },
};

export const LOGOUT_MESSAGE =
  "For your security, you've been logged out. Please sign in again.";
